# -*- coding: utf-8 -*-
"""NLQver2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14BJEbyEIFW5oe1j2Nsmi3Bm7ixNhBD3p
"""

!pip install transformers huggingface_hub

from huggingface_hub import notebook_login
notebook_login()  # hf token from hugging face account

from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

model_name = "tscholak/1wnr382e"
token = True

tokenizer = AutoTokenizer.from_pretrained(model_name, token=token)
model = AutoModelForSeq2SeqLM.from_pretrained(model_name, token=token)

schema = "Table students (id, name, age)"
question = "List the names of students older than the average  age"

#Q.List the names of students older than 20   Generated SQL: Question: select name from students where age > 20
#Q.List the average age of students           Generated SQL: Question: select avg(age) from students
#Q.List the names of students older than the average  age   Generated SQL: Question: select name from students where
#                                                                                    age > (select avg(age) from students)

prompt = f"{schema}\nQuestion: {question}\nSQL:"
inputs = tokenizer(prompt, return_tensors="pt")
outputs = model.generate(**inputs, max_length=128)

sql_query = tokenizer.decode(outputs[0], skip_special_tokens=True)
print("Generated SQL:", sql_query)
